name: Publish Development Docker image on Github

on:
  schedule:
  # Create weekly build
  - cron: '0 3 * * 6'

jobs:
  build:
    name: Build with AirPlay ${{ matrix.airplay_version }}
    strategy:
      matrix:
        airplay_version: [ "1", "2" ]
    uses: ./.github/workflows/docker-image-dev-reusable-workflow.yml
    with:
      airplay_version: ${{ matrix.airplay_version }}
    secrets: inherit
